spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goods-recommend?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  data:
    mongodb:
#      uri: mongodb://vps2:27017/xhs
      uri: mongodb://127.0.0.1:27017/goods
    elasticsearch:
#      cluster-name: elastic-bjc
#      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      local: true
      repositories:
        enable: true
server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level: debug
